export const WAIT_MARKETPLACE_ACCOUNTS_FETCH =
  "WAIT_MARKETPLACE_ACCOUNTS_FETCH";
export const WAIT_MARKETPLACE_ACCOUNT_ROLES_FETCH =
  "WAIT_MARKETPLACE_ACCOUNT_ROLES_FETCH";
export const WAIT_MARKETPLACE_ACCOUNT_ROLE_CREATE =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_CREATE";
export const WAIT_MARKETPLACE_ACCOUNT_ROLE_UPDATE =
  "WAIT_MARKETPLACE_ACCOUNT_ROLE_UPDATE";
export const WAIT_MARKETPLACE_ACCOUNT_ROLE_DELETE =
  "WAIT_MARKETPLACE_ACCOUNT_ROLE_DELETE";

export const WAIT_MARKETPLACE_ACCOUNT_EMAIL_INVITATIONS_FETCH =
  "WAIT_MARKETPLACE_ACCOUNT_EMAIL_INVITATIONS_FETCH";

export const NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_CREATED =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_CREATED";
export const NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_UPDATED =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_UPDATED";
export const NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_DELETED =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_DELETED";
export const NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_CREATED_FAILURE =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_CREATED_FAILURE";
export const NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_UPDATED_FAILURE =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_UPDATED_FAILURE";
export const NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_DELETED_FAILURE =
  "NOTIFICATION_MARKETPLACE_ACCOUNT_ROLE_DELETED_FAILURE";
