export const WAIT_MARKETPLACE_ACCOUNTS_FETCH =
  "WAIT_MARKETPLACE_ACCOUNTS_FETCH";

export const WAIT_MARKETPLACE_ACCOUNT_ROLES_FETCH =
  "WAIT_MARKETPLACE_ACCOUNT_ROLES_FETCH";

export const NOTIFICATION_ROLE_CREATED = "NOTIFICATION_ROLE_CREATED";
export const NOTIFICATION_ROLE_UPDATED = "NOTIFICATION_ROLE_UPDATED";
export const NOTIFICATION_ROLE_DELETED = "NOTIFICATION_ROLE_DELETED";
